//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewWorldMarket.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewWorldMarket.Core.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty
        ///Abyssal
        ///Electrified
        ///Empowered
        ///Ignited
        ///Frozen
        ///Arborea
        ///Brash
        ///Opportunist
        ///Retaliate
        ///Exhilarate
        ///Cruel
        ///Gambit
        ///Rally
        ///Abyssal Ward
        ///Fire Ward
        ///Lightning Ward
        ///Arcane Ward
        ///Ice Ward
        ///Nature Ward
        ///Slash Ward
        ///Strike Ward
        ///Thrust Ward
        ///Physical Ward
        ///Wilderness Ward
        ///Elemental Ward
        ///Spectral Ward
        ///Acid Resistance
        ///Abyssal
        ///Electrified
        ///Empowered
        ///Ignited
        ///Frozen
        ///Arboreal
        ///BrashI
        ///Opportunist
        ///Retaliate
        ///Exhilarate
        ///Cruel
        ///Gambit
        ///Rally
        ///Abyssal Ward
        ///Fire Ward
        ///Lightning Ward
        ///Arcane Ward
        ///Ice Wa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GemList {
            get {
                return ResourceManager.GetString("GemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empowering Whirling Blade
        ///Empowering Leaping Strike
        ///Bleeding Sweep
        ///Sundering Javeli
        ///Leeching Cyclone
        ///Fortifying Perforate
        ///Enfeebling Skewer
        ///Keen Vault Kick
        ///Voracious Blade
        ///Nullifying Oblivion
        ///Putrefying Scream
        ///Diminishing Orb
        ///Slowing Tether
        ///Refreshing Rupture
        ///Empowering Armor Breaker
        ///Refreshing Mighty Gavel
        ///Penetrating Wrecking Ball
        ///Sundering Shockwave
        ///Repulsing Clear Out
        ///Leeching Path Of Destiny
        ///Sturdy
        ///Sure Footing
        ///Refreshing
        ///Refreshing Ward
        ///Refreshing Evasi
        ///Keen
        ///Enchanted
        ///Ruinou [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PerkListV2 {
            get {
                return ResourceManager.GetString("PerkListV2", resourceCulture);
            }
        }
    }
}
