namespace NewWorld.BiSMarket.Core.Constants;

public enum ItemType
{
    Sword,
    Shield,
    Rapier,
    Hatchet,
    Spear,
    Great_Axe,
    War_Hammer,
    Greatsword,
    Bow,
    Musket,
    Blunderbuss,
    Fire_Staff,
    Ice_Gauntlet,
    Life_Staff,
    Void_Gauntlet,
    Heavy_Headwear,
    Heavy_Chestwear,
    Heavy_Footwear,
    Heavy_Legwear,
    Heavy_Glove,
    Medium_Headwear,
    Medium_Chestwear,
    Medium_Footwear,
    Medium_Legwear,
    Medium_Glove,
    Light_Headwear,
    Light_Chestwear,
    Light_Footwear,
    Light_Legwear,
    Light_Glove,
    Amulet,
    Ring,
    Earring
}